os:
  - linux
language: java
node_js:
  - "4.2.1"
jdk:
  - oraclejdk8
before_install: 
  - rm /home/travis/.npm/4a5c1cea-s-npm-minimist-1-2-0-package-tgz.lock
install:
  - java -version
  - mvn --version
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install
  - mvn clean package
