os:
  - linux
language: java
node_js:
  - "4.2.1"
jdk:
  - oraclejdk8
before_install: npm install -g grunt-cli
install:
  - java -version
  - mvn --version
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install
  - mvn clean package
